name: TruffleHog Secret Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  trufflehog:
    name: Run TruffleHog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: pip install truffleHog

      - name: Run TruffleHog Scan
        run: |
          trufflehog git --json . > trufflehog-report.json || true

      - name: Convert TruffleHog JSON report to HTML
        run: |
          echo "<html><body><h1>TruffleHog Report</h1><pre>" > trufflehog-report.html
          cat trufflehog-report.json >> trufflehog-report.html
          echo "</pre></body></html>" >> trufflehog-report.html

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog-report.html
